### PR TITLE
same edit for clan.

### PR DESCRIPTION
**Pull request by erickang21**
plz don't turn this down, i think it's gud :) p.s. sharpbit, let the others check it before you turn it down lol

### CODE REVIEW

**Comment by Epsilon10** [comment]
Might as well accept this it should work.

**Comment by aj20418** [comment]
I'll get the others to check it out before we merge anything

**Comment by umbresp** [comment]
fix the indentation pls

**Comment by SharpBit** [comment]
we're keeping crowns as it's better info than tiers, and clan command is down anyway /shrug

**Pull request closed without merging**
